//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace custom_image_downloader.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("custom_image_downloader.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelled.
        /// </summary>
        internal static string CancelledTitle {
            get {
                return ResourceManager.GetString("CancelledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download cancelled. Partial files were deleted..
        /// </summary>
        internal static string DownloadCancelledMessage {
            get {
                return ResourceManager.GetString("DownloadCancelledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download cancelled..
        /// </summary>
        internal static string DownloadCancelledStatus {
            get {
                return ResourceManager.GetString("DownloadCancelledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download completed!
        ///
        ///• Successful: {0}
        ///• Failures: {1}
        ///
        ///Do you want to open the folder now?.
        /// </summary>
        internal static string DownloadCompletedMessage {
            get {
                return ResourceManager.GetString("DownloadCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total failure. Nothing was downloaded.
        ///Errors: {0}.
        /// </summary>
        internal static string DownloadFailedMessage {
            get {
                return ResourceManager.GetString("DownloadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download failed!.
        /// </summary>
        internal static string DownloadFailedStatus {
            get {
                return ResourceManager.GetString("DownloadFailedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error creating folder &apos;{0}&apos; in path &apos;{1}&apos;.
        /// </summary>
        internal static string ErrorCreatingFolderMessage {
            get {
                return ResourceManager.GetString("ErrorCreatingFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fatal Error.
        /// </summary>
        internal static string FatalErrorTitle {
            get {
                return ResourceManager.GetString("FatalErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the folder where files will be saved.
        /// </summary>
        internal static string FolderBrowserDescription {
            get {
                return ResourceManager.GetString("FolderBrowserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pause.
        /// </summary>
        internal static string PauseButtonText {
            get {
                return ResourceManager.GetString("PauseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resume.
        /// </summary>
        internal static string ResumeButtonText {
            get {
                return ResourceManager.GetString("ResumeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paused (Completed {0} of {1})....
        /// </summary>
        internal static string Status_Paused {
            get {
                return ResourceManager.GetString("Status_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Processing {0} of {1}....
        /// </summary>
        internal static string Status_Processing {
            get {
                return ResourceManager.GetString("Status_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Starting {0} downloads....
        /// </summary>
        internal static string Status_Starting {
            get {
                return ResourceManager.GetString("Status_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success.
        /// </summary>
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string UI_btnCancelar_Text {
            get {
                return ResourceManager.GetString("UI_btnCancelar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download.
        /// </summary>
        internal static string UI_btnDescargar_Text {
            get {
                return ResourceManager.GetString("UI_btnDescargar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browse....
        /// </summary>
        internal static string UI_btnSeleccionarCarpeta_Text {
            get {
                return ResourceManager.GetString("UI_btnSeleccionarCarpeta_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bulk image downloader.
        /// </summary>
        internal static string UI_Form_Text {
            get {
                return ResourceManager.GetString("UI_Form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simultaneous downloads:.
        /// </summary>
        internal static string UI_label1_Text {
            get {
                return ResourceManager.GetString("UI_label1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready.
        /// </summary>
        internal static string UI_lblEstado_Text {
            get {
                return ResourceManager.GetString("UI_lblEstado_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destination path.
        /// </summary>
        internal static string UI_txtCarpeta_PlaceholderText {
            get {
                return ResourceManager.GetString("UI_txtCarpeta_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subfolder.
        /// </summary>
        internal static string UI_txtNombreBase_PlaceholderText {
            get {
                return ResourceManager.GetString("UI_txtNombreBase_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URLs (one URL per line).
        /// </summary>
        internal static string UI_txtUrls_PlaceholderText {
            get {
                return ResourceManager.GetString("UI_txtUrls_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unexpected error during download, check the logs for further details..
        /// </summary>
        internal static string UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please verify:
        ///        
        ///1. That there is at least one URL.
        ///2. That the Parent Path exists.
        ///3. That you provided a name for the subfolder..
        /// </summary>
        internal static string ValidationErrorMessage {
            get {
                return ResourceManager.GetString("ValidationErrorMessage", resourceCulture);
            }
        }
    }
}
